### ISSUE TITLE
Style Voting Page

### ISSUE THREAD

**Issue by alexhoffman617** [excellalabs/excella-retro-2#60]
The voting page needs a little bit of formatting before its mvp ready

- [ ] have text, votes, and add vote button all be inline between cards
- [ ] Make groups full-width of step container

**Comment by samblissard** [comment]
@alexhoffman617 please add more focused tasks that should be done for this whenever you get a chance

**Comment by alexhoffman617** [comment]
@samblissard https://media.tenor.co/images/e58414f3363a5637fc4470bd88cc2656/tenor.gif
